# Generated by Django 5.0.4 on 2024-05-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocks",
            name="hood_id",
            field=models.ForeignKey(
                db_column="hood_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.hoods",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="addr_id",
            field=models.ForeignKey(
                db_column="addr_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.address",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_photo",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
