# Generated by Django 5.0.4 on 2024-05-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_blocks_hood_id_alter_users_addr_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="hood_id",
            field=models.ForeignKey(
                db_column="hood_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.hoods",
            ),
        ),
    ]
