# Generated by Django 5.0.4 on 2024-05-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_applications_applicant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="first_sender_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.users",
            ),
        ),
    ]
