# Generated by Django 5.0.4 on 2024-05-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_thread_first_sender_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="votes",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="votes",
            name="application_id",
            field=models.ForeignKey(
                db_column="application_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.applications",
                unique=True,
            ),
        ),
    ]
