# Generated by Django 5.0.4 on 2024-05-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_votes_vote_count_alter_votes_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoods",
            name="hood_id",
            field=models.AutoField(
                db_column="hood_id", primary_key=True, serialize=False
            ),
        ),
    ]
